CC = g++
CFLAGS =  -g -Wall

all: csv_matrix.h stopwatch.h
	$(CC) $(CFLAGS) -o test testing.cc csv_matrix.cc 


# testing : data.o testing.o
# 	$(CC) $(CFLAGS) -o test data.o testing.o

# data.o : data.cc data.h
# 	$(CC) $(CFLAGS)	data.cc

# testing.o : testing.cc
# 	$(CC) $(CFLAGS) testing.cc