CC = g++
CFLAGS =  -g -Wall -std=c++17

all: csv_matrix.h stopwatch.h
	$(CC) $(CFLAGS) -o test.out testing.cc

# all: testing

# testing : testing.o csv_matrix.h stopwatch.h
# 	$(CC) $(CFLAGS) -o test.out

# clean: 
# 	$(RM) testing *.o *~